#!/usr/bin/env bash
# ============================================================================
# ramp-fix-useramp-endorsements.sh
#
# CORRECTIVE PATCH (web). Companion to ramp-fix-customers-endorsements.sh.
# Phase 2b applied only partially: app/(app)/ramp/page.tsx got the endorsement
# grid (it calls useOnramp().endorsementFor), but hooks/useRamp.ts never
# received endorsementFor / loadEndorsements — so `tsc` fails with TS2339
# "Property 'endorsementFor' does not exist".
#
# This restores hooks/useRamp.ts to the correct Phase-2b version, a strict
# SUPERSET of the original: it only ADDS the endorsement state, loadEndorsements(),
# and endorsementFor(), and wires them into useOnramp's effect + return. Nothing
# else changes. Safety-checked: the new file must still export useRamp, useOnramp,
# createVirtualAccount, and getActivity before it is placed.
#
# Safe: whole-file replace with backup + --revert, idempotent (marker guard).
#
# Usage:
#   bash ramp-fix-useramp-endorsements.sh           # apply
#   bash ramp-fix-useramp-endorsements.sh --revert  # restore
# ============================================================================
set -euo pipefail

find_web_dir() {
  for d in "nexum-web" "afrifx-web" "." "../nexum-web" "../afrifx-web"; do
    if [ -f "$d/package.json" ] && [ -f "$d/hooks/useRamp.ts" ]; then
      (cd "$d" && pwd); return 0
    fi
  done
  return 1
}
WEB_DIR="$(find_web_dir || true)"
if [ -z "${WEB_DIR:-}" ]; then echo "✗ Could not find the web package." >&2; exit 1; fi
echo "• Web package: $WEB_DIR"

STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR="$WEB_DIR/.ramp-fix-useramp-backup"
F_HOOK="hooks/useRamp.ts"
MARKER="endorsementFor"

if [ "${1:-}" = "--revert" ]; then
  if [ ! -d "$BACKUP_DIR" ]; then echo "✗ No backups." >&2; exit 1; fi
  LATEST="$(ls -1 "$BACKUP_DIR" | sed -n 's/^manifest-\(.*\)\.txt$/\1/p' | sort | tail -1 || true)"
  if [ -z "${LATEST:-}" ]; then echo "✗ No manifest." >&2; exit 1; fi
  bak="$BACKUP_DIR/${F_HOOK//\//__}.$LATEST.bak"
  if [ -f "$bak" ]; then cp -f "$bak" "$WEB_DIR/$F_HOOK"; echo "  ↺ restored $F_HOOK"; else echo "✗ missing backup" >&2; exit 1; fi
  echo "✓ Revert complete."; exit 0
fi

if [ -f "$WEB_DIR/$F_HOOK" ] && grep -qF "$MARKER" "$WEB_DIR/$F_HOOK"; then
  echo "✓ useRamp.ts already has endorsementFor. Nothing to do."; exit 0
fi

mkdir -p "$BACKUP_DIR"
MANIFEST="$BACKUP_DIR/manifest-$STAMP.txt"; : > "$MANIFEST"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT

echo "• Restoring useRamp.ts (Phase 2b version) …"

# ---- FIXHOOK ----
cat > "$WORK/FIXHOOK.b64" <<'B64_FIXHOOK'
J3VzZSBjbGllbnQnCmltcG9ydCB7IHVzZVN0YXRlLCB1c2VDYWxsYmFjaywgdXNlRWZmZWN0IH0g
ZnJvbSAncmVhY3QnCmltcG9ydCB7IGFwaUZldGNoIH0gZnJvbSAnQC9ob29rcy91c2VBdXRoJwoK
ZXhwb3J0IHR5cGUgUmFtcEt5Y1N0YXR1cyA9CiAgfCAnbm90X3N0YXJ0ZWQnIHwgJ3VuZGVyX3Jl
dmlldycgfCAnaW5jb21wbGV0ZScKICB8ICdhd2FpdGluZ19xdWVzdGlvbm5haXJlJyB8ICdhd2Fp
dGluZ191Ym8nCiAgfCAnYXBwcm92ZWQnIHwgJ3JlamVjdGVkJyB8ICdwYXVzZWQnIHwgJ29mZmJv
YXJkZWQnCgpleHBvcnQgdHlwZSBSYW1wVG9zU3RhdHVzID0gJ3BlbmRpbmcnIHwgJ2FwcHJvdmVk
JwpleHBvcnQgdHlwZSBSYW1wQ3VzdG9tZXJUeXBlID0gJ2luZGl2aWR1YWwnIHwgJ2J1c2luZXNz
JwoKZXhwb3J0IGludGVyZmFjZSBSYW1wUmVqZWN0aW9uIHsKICBkZXZlbG9wZXJfcmVhc29uPzog
c3RyaW5nCiAgcmVhc29uPzogc3RyaW5nCiAgY3JlYXRlZF9hdD86IHN0cmluZwp9CgpleHBvcnQg
aW50ZXJmYWNlIFJhbXBDdXN0b21lciB7CiAgZXhpc3RzOiAgICAgICBib29sZWFuCiAgY3VzdG9t
ZXJUeXBlPzogUmFtcEN1c3RvbWVyVHlwZQogIGt5Y1N0YXR1cz86ICAgUmFtcEt5Y1N0YXR1cwog
IHRvc1N0YXR1cz86ICAgUmFtcFRvc1N0YXR1cwogIGt5Y0xpbms/OiAgICAgc3RyaW5nIHwgbnVs
bAogIHRvc0xpbms/OiAgICAgc3RyaW5nIHwgbnVsbAogIGN1c3RvbWVySWQ/OiAgc3RyaW5nIHwg
bnVsbAogIHJlamVjdGlvblJlYXNvbnM/OiBSYW1wUmVqZWN0aW9uW10KICB2ZXJpZmllZD86ICAg
IGJvb2xlYW4KfQoKLy8g4pSA4pSAIFBoYXNlIDI6IGNvcnJpZG9ycyArIHZpcnR1YWwgYWNjb3Vu
dHMg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA
4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACgpleHBvcnQg
aW50ZXJmYWNlIFJhbXBDb3JyaWRvciB7CiAgY3VycmVuY3k6ICBzdHJpbmcgICAgICAgICAgIC8v
IGxvd2VyLWNhc2UgSVNPICgndXNkJykKICBsYWJlbDogICAgIHN0cmluZwogIG1pbkFtb3VudD86
IG51bWJlcgp9CgovLyBCcmlkZ2UncyBzb3VyY2VfZGVwb3NpdF9pbnN0cnVjdGlvbnM6IGZpZWxk
IHNldCB2YXJpZXMgYnkgY3VycmVuY3ksIHNvIHRoaXMKLy8gaXMgaW50ZW50aW9uYWxseSBvcGVu
LiBUaGUgVUkgcmVuZGVycyB3aGljaGV2ZXIgZmllbGRzIGFyZSBwcmVzZW50LgpleHBvcnQgaW50
ZXJmYWNlIERlcG9zaXRJbnN0cnVjdGlvbnMgewogIGN1cnJlbmN5PzogICAgICAgICAgICAgICBz
dHJpbmcKICBwYXltZW50X3JhaWw/OiAgICAgICAgICAgc3RyaW5nCiAgcGF5bWVudF9yYWlscz86
ICAgICAgICAgIHN0cmluZ1tdCiAgYmFua19uYW1lPzogICAgICAgICAgICAgIHN0cmluZwogIGJh
bmtfYWRkcmVzcz86ICAgICAgICAgICBzdHJpbmcKICBiYW5rX3JvdXRpbmdfbnVtYmVyPzogICAg
c3RyaW5nCiAgYmFua19hY2NvdW50X251bWJlcj86ICAgIHN0cmluZwogIGJhbmtfYmVuZWZpY2lh
cnlfbmFtZT86ICBzdHJpbmcKICBiYW5rX2JlbmVmaWNpYXJ5X2FkZHJlc3M/OiBzdHJpbmcKICBp
YmFuPzogICAgICAgICAgICAgICAgICAgc3RyaW5nCiAgYmljPzogICAgICAgICAgICAgICAgICAg
IHN0cmluZwogIGFjY291bnRfaG9sZGVyX25hbWU/OiAgICBzdHJpbmcKICBjbGFiZT86ICAgICAg
ICAgICAgICAgICAgc3RyaW5nCiAgYnJfY29kZT86ICAgICAgICAgICAgICAgIHN0cmluZwogIGFj
Y291bnRfbnVtYmVyPzogICAgICAgICBzdHJpbmcKICBzb3J0X2NvZGU/OiAgICAgICAgICAgICAg
c3RyaW5nCiAgW2tleTogc3RyaW5nXTogdW5rbm93bgp9CgpleHBvcnQgaW50ZXJmYWNlIFJhbXBW
aXJ0dWFsQWNjb3VudCB7CiAgY3VycmVuY3k6ICAgICAgICAgICAgc3RyaW5nCiAgdmlydHVhbEFj
Y291bnRJZDogICAgc3RyaW5nCiAgZGVzdGluYXRpb25BZGRyZXNzOiAgc3RyaW5nCiAgZGVzdGlu
YXRpb25DaGFpbjogICAgc3RyaW5nCiAgc3RhdHVzOiAgICAgICAgICAgICAgc3RyaW5nCiAgZGVw
b3NpdEluc3RydWN0aW9uczogRGVwb3NpdEluc3RydWN0aW9ucyB8IG51bGwKICBjcmVhdGVkQXQ6
ICAgICAgICAgICBudW1iZXIKfQoKZXhwb3J0IGludGVyZmFjZSBSYW1wQWN0aXZpdHlFdmVudCB7
CiAgaWQ6ICAgICAgICAgICAgICAgICAgc3RyaW5nCiAgdHlwZTogICAgICAgICAgICAgICAgc3Ry
aW5nCiAgYW1vdW50PzogICAgICAgICAgICAgc3RyaW5nCiAgY3VycmVuY3k/OiAgICAgICAgICAg
c3RyaW5nCiAgY3JlYXRlZF9hdD86ICAgICAgICAgc3RyaW5nCiAgZGVwb3NpdF9pZD86ICAgICAg
ICAgc3RyaW5nCiAgZGVzdGluYXRpb25fdHhfaGFzaD86IHN0cmluZwogIHJlY2VpcHQ/OiB7IHVy
bD86IHN0cmluZzsgZmluYWxfYW1vdW50Pzogc3RyaW5nOyBbazogc3RyaW5nXTogdW5rbm93biB9
CiAgW2tleTogc3RyaW5nXTogdW5rbm93bgp9CgovKgogIEJyaWRnZS54eXogb25ib2FyZGluZyBz
dGF0ZSBmb3IgdGhlIHNpZ25lZC1pbiBhY2NvdW50LiBLWUMgaXMgaG9zdGVkICh0aGUKICB1c2Vy
IGNvbXBsZXRlcyB0b3NfbGluayArIGt5Y19saW5rIGluIGEgbmV3IHRhYiksIHNvIHRoaXMgaG9v
aydzIGpvYiBpcyB0bwogIGNyZWF0ZSB0aGUgbGluaywgZXhwb3NlIGl0LCBhbmQgcG9sbCBzdGF0
dXMgdW50aWwgYXBwcm92ZWQvcmVqZWN0ZWQuCiovCmV4cG9ydCBmdW5jdGlvbiB1c2VSYW1wKCkg
ewogIGNvbnN0IFtjdXN0b21lciwgc2V0Q3VzdG9tZXJdID0gdXNlU3RhdGU8UmFtcEN1c3RvbWVy
IHwgbnVsbD4obnVsbCkKICBjb25zdCBbbG9hZGluZywgIHNldExvYWRpbmddICA9IHVzZVN0YXRl
KHRydWUpCiAgY29uc3QgW2J1c3ksICAgICBzZXRCdXN5XSAgICAgPSB1c2VTdGF0ZShmYWxzZSkK
ICBjb25zdCBbZXJyb3IsICAgIHNldEVycm9yXSAgICA9IHVzZVN0YXRlPHN0cmluZyB8IG51bGw+
KG51bGwpCgogIGNvbnN0IGxvYWQgPSB1c2VDYWxsYmFjayhhc3luYyAoKSA9PiB7CiAgICBzZXRM
b2FkaW5nKHRydWUpOyBzZXRFcnJvcihudWxsKQogICAgdHJ5IHsKICAgICAgY29uc3QgcmVzID0g
YXdhaXQgYXBpRmV0Y2goJy9yYW1wL2N1c3RvbWVyJykKICAgICAgY29uc3QgZGF0YSA9IGF3YWl0
IHJlcy5qc29uKCkuY2F0Y2goKCkgPT4gKHt9KSkKICAgICAgaWYgKCFyZXMub2spIHRocm93IG5l
dyBFcnJvcihkYXRhLmVycm9yID8/ICdDb3VsZCBub3QgbG9hZCB5b3VyIHJhbXAgc3RhdHVzJykK
ICAgICAgc2V0Q3VzdG9tZXIoZGF0YSkKICAgIH0gY2F0Y2ggKGVycjogYW55KSB7CiAgICAgIHNl
dEVycm9yKGVycj8ubWVzc2FnZSA/PyAnQ291bGQgbm90IGxvYWQgeW91ciByYW1wIHN0YXR1cycp
CiAgICB9IGZpbmFsbHkgewogICAgICBzZXRMb2FkaW5nKGZhbHNlKQogICAgfQogIH0sIFtdKQoK
ICB1c2VFZmZlY3QoKCkgPT4geyBsb2FkKCkgfSwgW2xvYWRdKQoKICAvLyBDcmVhdGUgdGhlIGhv
c3RlZCBLWUMgbGluayAobGF6eSBvbmJvYXJkaW5nKS4KICBjb25zdCBzdGFydFZlcmlmaWNhdGlv
biA9IHVzZUNhbGxiYWNrKGFzeW5jIChmdWxsTmFtZTogc3RyaW5nLCB0eXBlOiBSYW1wQ3VzdG9t
ZXJUeXBlKSA9PiB7CiAgICBzZXRCdXN5KHRydWUpOyBzZXRFcnJvcihudWxsKQogICAgdHJ5IHsK
ICAgICAgY29uc3QgcmVzID0gYXdhaXQgYXBpRmV0Y2goJy9yYW1wL2N1c3RvbWVyJywgewogICAg
ICAgIG1ldGhvZDogJ1BPU1QnLAogICAgICAgIGJvZHk6IEpTT04uc3RyaW5naWZ5KHsgZnVsbE5h
bWUsIHR5cGUgfSksCiAgICAgIH0pCiAgICAgIGNvbnN0IGRhdGEgPSBhd2FpdCByZXMuanNvbigp
LmNhdGNoKCgpID0+ICh7fSkpCiAgICAgIGlmICghcmVzLm9rKSB0aHJvdyBuZXcgRXJyb3IoZGF0
YS5lcnJvciA/PyAnQ291bGQgbm90IHN0YXJ0IHZlcmlmaWNhdGlvbicpCiAgICAgIHNldEN1c3Rv
bWVyKGRhdGEpCiAgICAgIHJldHVybiBkYXRhIGFzIFJhbXBDdXN0b21lcgogICAgfSBjYXRjaCAo
ZXJyOiBhbnkpIHsKICAgICAgc2V0RXJyb3IoZXJyPy5tZXNzYWdlID8/ICdDb3VsZCBub3Qgc3Rh
cnQgdmVyaWZpY2F0aW9uJykKICAgICAgcmV0dXJuIG51bGwKICAgIH0gZmluYWxseSB7CiAgICAg
IHNldEJ1c3koZmFsc2UpCiAgICB9CiAgfSwgW10pCgogIC8vIFBvbGwgQnJpZGdlIGZvciB0aGUg
bGF0ZXN0IHN0YXR1cyAoY2FsbGVkIG9uIHRhYi1yZXR1cm4gLyBpbnRlcnZhbCkuCiAgY29uc3Qg
cmVmcmVzaCA9IHVzZUNhbGxiYWNrKGFzeW5jICgpID0+IHsKICAgIHRyeSB7CiAgICAgIGNvbnN0
IHJlcyA9IGF3YWl0IGFwaUZldGNoKCcvcmFtcC9jdXN0b21lci9yZWZyZXNoJykKICAgICAgY29u
c3QgZGF0YSA9IGF3YWl0IHJlcy5qc29uKCkuY2F0Y2goKCkgPT4gKHt9KSkKICAgICAgaWYgKHJl
cy5vaykgc2V0Q3VzdG9tZXIoZGF0YSkKICAgICAgcmV0dXJuIGRhdGEgYXMgUmFtcEN1c3RvbWVy
CiAgICB9IGNhdGNoIHsgcmV0dXJuIG51bGwgfQogIH0sIFtdKQoKICAvLyBTYW5kYm94LW9ubHkg
aGVscGVyIHRoZSBVSSBzaG93cyBiZWhpbmQgYW4gZW52IGZsYWcuCiAgY29uc3Qgc2ltdWxhdGVB
cHByb3ZlID0gdXNlQ2FsbGJhY2soYXN5bmMgKCkgPT4gewogICAgc2V0QnVzeSh0cnVlKTsgc2V0
RXJyb3IobnVsbCkKICAgIHRyeSB7CiAgICAgIGNvbnN0IHJlcyA9IGF3YWl0IGFwaUZldGNoKCcv
cmFtcC9jdXN0b21lci9zaW11bGF0ZS1hcHByb3ZlJywgeyBtZXRob2Q6ICdQT1NUJyB9KQogICAg
ICBjb25zdCBkYXRhID0gYXdhaXQgcmVzLmpzb24oKS5jYXRjaCgoKSA9PiAoe30pKQogICAgICBp
ZiAoIXJlcy5vaykgdGhyb3cgbmV3IEVycm9yKGRhdGEuZXJyb3IgPz8gJ1NpbXVsYXRlIGFwcHJv
dmFsIGZhaWxlZCcpCiAgICAgIHNldEN1c3RvbWVyKGRhdGEpCiAgICAgIHJldHVybiBkYXRhIGFz
IFJhbXBDdXN0b21lcgogICAgfSBjYXRjaCAoZXJyOiBhbnkpIHsKICAgICAgc2V0RXJyb3IoZXJy
Py5tZXNzYWdlID8/ICdTaW11bGF0ZSBhcHByb3ZhbCBmYWlsZWQnKQogICAgICByZXR1cm4gbnVs
bAogICAgfSBmaW5hbGx5IHsKICAgICAgc2V0QnVzeShmYWxzZSkKICAgIH0KICB9LCBbXSkKCiAg
Y29uc3QgdmVyaWZpZWQgPSAhIWN1c3RvbWVyPy52ZXJpZmllZAoKICByZXR1cm4geyBjdXN0b21l
ciwgbG9hZGluZywgYnVzeSwgZXJyb3IsIHZlcmlmaWVkLCBsb2FkLCBzdGFydFZlcmlmaWNhdGlv
biwgcmVmcmVzaCwgc2ltdWxhdGVBcHByb3ZlIH0KfQoKLyoKICBQaGFzZSAyIG9uLXJhbXAgaG9v
azogY29ycmlkb3JzLCB2aXJ0dWFsLWFjY291bnQgY3JlYXRpb24sIGFuZCBkZXBvc2l0CiAgYWN0
aXZpdHkuIEtlcHQgc2VwYXJhdGUgZnJvbSB1c2VSYW1wKCkgc28gdGhlIEtZQy1nYXRlIHN1cmZh
Y2UgaXMgdW50b3VjaGVkLgogIEFsbCBjYWxscyBnbyB0aHJvdWdoIGFwaUZldGNoLCB3aGljaCBh
dHRhY2hlcyB0aGUgc2Vzc2lvbiBhdXRvbWF0aWNhbGx5LgoqLwpleHBvcnQgZnVuY3Rpb24gdXNl
T25yYW1wKCkgewogIGNvbnN0IFtjb3JyaWRvcnMsIHNldENvcnJpZG9yc10gICAgICAgICAgID0g
dXNlU3RhdGU8UmFtcENvcnJpZG9yW10+KFtdKQogIGNvbnN0IFtjb3JyaWRvcnNMb2FkaW5nLCBz
ZXRDb3JyaWRvcnNMb2FkaW5nXSA9IHVzZVN0YXRlKHRydWUpCiAgY29uc3QgW3ZpcnR1YWxBY2Nv
dW50cywgc2V0VmlydHVhbEFjY291bnRzXSA9IHVzZVN0YXRlPFJhbXBWaXJ0dWFsQWNjb3VudFtd
PihbXSkKICBjb25zdCBbZW5kb3JzZW1lbnRzLCBzZXRFbmRvcnNlbWVudHNdICAgICA9IHVzZVN0
YXRlPFJlY29yZDxzdHJpbmcsIHsgc3RhdHVzOiBzdHJpbmc7IGFwcHJvdmVkOiBib29sZWFuIH0+
Pih7fSkKICBjb25zdCBbY3JlYXRpbmcsIHNldENyZWF0aW5nXSAgICAgICAgICAgICA9IHVzZVN0
YXRlKGZhbHNlKQogIGNvbnN0IFtlcnJvciwgc2V0RXJyb3JdICAgICAgICAgICAgICAgICAgID0g
dXNlU3RhdGU8c3RyaW5nIHwgbnVsbD4obnVsbCkKCiAgY29uc3QgbG9hZENvcnJpZG9ycyA9IHVz
ZUNhbGxiYWNrKGFzeW5jICgpID0+IHsKICAgIHNldENvcnJpZG9yc0xvYWRpbmcodHJ1ZSkKICAg
IHRyeSB7CiAgICAgIGNvbnN0IHJlcyA9IGF3YWl0IGFwaUZldGNoKCcvcmFtcC9jb3JyaWRvcnMn
KQogICAgICBjb25zdCBkYXRhID0gYXdhaXQgcmVzLmpzb24oKS5jYXRjaCgoKSA9PiAoe30pKQog
ICAgICBpZiAocmVzLm9rICYmIEFycmF5LmlzQXJyYXkoZGF0YS5vbnJhbXApKSBzZXRDb3JyaWRv
cnMoZGF0YS5vbnJhbXApCiAgICB9IGNhdGNoIHsgLyogbGVhdmUgZW1wdHk7IHRoZSBwYWdlIHNo
b3dzIGFuIGVtcHR5IHN0YXRlICovIH0KICAgIGZpbmFsbHkgeyBzZXRDb3JyaWRvcnNMb2FkaW5n
KGZhbHNlKSB9CiAgfSwgW10pCgogIGNvbnN0IGxvYWRFbmRvcnNlbWVudHMgPSB1c2VDYWxsYmFj
ayhhc3luYyAoKSA9PiB7CiAgICB0cnkgewogICAgICBjb25zdCByZXMgPSBhd2FpdCBhcGlGZXRj
aCgnL3JhbXAvZW5kb3JzZW1lbnRzJykKICAgICAgY29uc3QgZGF0YSA9IGF3YWl0IHJlcy5qc29u
KCkuY2F0Y2goKCkgPT4gKHt9KSkKICAgICAgaWYgKHJlcy5vayAmJiBkYXRhLmVuZG9yc2VtZW50
cyAmJiB0eXBlb2YgZGF0YS5lbmRvcnNlbWVudHMgPT09ICdvYmplY3QnKSB7CiAgICAgICAgc2V0
RW5kb3JzZW1lbnRzKGRhdGEuZW5kb3JzZW1lbnRzKQogICAgICB9CiAgICB9IGNhdGNoIHsgLyog
bm9uLWZhdGFsOyBncmlkIGZhbGxzIGJhY2sgdG8gImNoZWNraW5nIiAqLyB9CiAgfSwgW10pCgog
IGNvbnN0IGxvYWRWaXJ0dWFsQWNjb3VudHMgPSB1c2VDYWxsYmFjayhhc3luYyAoKSA9PiB7CiAg
ICB0cnkgewogICAgICBjb25zdCByZXMgPSBhd2FpdCBhcGlGZXRjaCgnL3JhbXAvdmlydHVhbC1h
Y2NvdW50cycpCiAgICAgIGNvbnN0IGRhdGEgPSBhd2FpdCByZXMuanNvbigpLmNhdGNoKCgpID0+
ICh7fSkpCiAgICAgIGlmIChyZXMub2sgJiYgQXJyYXkuaXNBcnJheShkYXRhLnZpcnR1YWxBY2Nv
dW50cykpIHsKICAgICAgICBzZXRWaXJ0dWFsQWNjb3VudHMoZGF0YS52aXJ0dWFsQWNjb3VudHMp
CiAgICAgIH0KICAgIH0gY2F0Y2ggeyAvKiBub24tZmF0YWwgKi8gfQogIH0sIFtdKQoKICB1c2VF
ZmZlY3QoKCkgPT4gewogICAgbG9hZENvcnJpZG9ycygpOyBsb2FkVmlydHVhbEFjY291bnRzKCk7
IGxvYWRFbmRvcnNlbWVudHMoKQogIH0sIFtsb2FkQ29ycmlkb3JzLCBsb2FkVmlydHVhbEFjY291
bnRzLCBsb2FkRW5kb3JzZW1lbnRzXSkKCiAgLy8gQ3JlYXRlIChvciBmZXRjaCBleGlzdGluZykg
dGhlIGRlcG9zaXQgYWNjb3VudCBmb3IgYSBjdXJyZW5jeS4gUmV0dXJucyB0aGUKICAvLyB2aXJ0
dWFsIGFjY291bnQsIG9yIG51bGwgb24gZXJyb3IgKGVycm9yIHN0YXRlIGlzIHNldCkuCiAgY29u
c3QgY3JlYXRlVmlydHVhbEFjY291bnQgPSB1c2VDYWxsYmFjayhhc3luYyAoY3VycmVuY3k6IHN0
cmluZykgPT4gewogICAgc2V0Q3JlYXRpbmcodHJ1ZSk7IHNldEVycm9yKG51bGwpCiAgICB0cnkg
ewogICAgICBjb25zdCByZXMgPSBhd2FpdCBhcGlGZXRjaCgnL3JhbXAvdmlydHVhbC1hY2NvdW50
JywgewogICAgICAgIG1ldGhvZDogJ1BPU1QnLAogICAgICAgIGJvZHk6IEpTT04uc3RyaW5naWZ5
KHsgY3VycmVuY3kgfSksCiAgICAgIH0pCiAgICAgIGNvbnN0IGRhdGEgPSBhd2FpdCByZXMuanNv
bigpLmNhdGNoKCgpID0+ICh7fSkpCiAgICAgIGlmICghcmVzLm9rKSB0aHJvdyBuZXcgRXJyb3Io
ZGF0YS5lcnJvciA/PyAnQ291bGQgbm90IHNldCB1cCBkZXBvc2l0cycpCiAgICAgIGNvbnN0IHZh
ID0gZGF0YS52aXJ0dWFsQWNjb3VudCBhcyBSYW1wVmlydHVhbEFjY291bnQKICAgICAgc2V0Vmly
dHVhbEFjY291bnRzKHByZXYgPT4gewogICAgICAgIGNvbnN0IHJlc3QgPSBwcmV2LmZpbHRlcih2
ID0+IHYuY3VycmVuY3kgIT09IHZhLmN1cnJlbmN5KQogICAgICAgIHJldHVybiBbLi4ucmVzdCwg
dmFdCiAgICAgIH0pCiAgICAgIHJldHVybiB2YQogICAgfSBjYXRjaCAoZXJyOiBhbnkpIHsKICAg
ICAgc2V0RXJyb3IoZXJyPy5tZXNzYWdlID8/ICdDb3VsZCBub3Qgc2V0IHVwIGRlcG9zaXRzJykK
ICAgICAgcmV0dXJuIG51bGwKICAgIH0gZmluYWxseSB7CiAgICAgIHNldENyZWF0aW5nKGZhbHNl
KQogICAgfQogIH0sIFtdKQoKICBjb25zdCBnZXRBY3Rpdml0eSA9IHVzZUNhbGxiYWNrKGFzeW5j
IChjdXJyZW5jeTogc3RyaW5nKSA9PiB7CiAgICB0cnkgewogICAgICBjb25zdCByZXMgPSBhd2Fp
dCBhcGlGZXRjaChgL3JhbXAvdmlydHVhbC1hY2NvdW50LyR7Y3VycmVuY3l9L2FjdGl2aXR5YCkK
ICAgICAgY29uc3QgZGF0YSA9IGF3YWl0IHJlcy5qc29uKCkuY2F0Y2goKCkgPT4gKHt9KSkKICAg
ICAgaWYgKCFyZXMub2spIHJldHVybiBudWxsCiAgICAgIHJldHVybiB7CiAgICAgICAgY291bnQ6
ICBOdW1iZXIoZGF0YS5jb3VudCA/PyAwKSwKICAgICAgICBldmVudHM6IEFycmF5LmlzQXJyYXko
ZGF0YS5ldmVudHMpID8gKGRhdGEuZXZlbnRzIGFzIFJhbXBBY3Rpdml0eUV2ZW50W10pIDogW10s
CiAgICAgIH0KICAgIH0gY2F0Y2ggeyByZXR1cm4gbnVsbCB9CiAgfSwgW10pCgogIGNvbnN0IGZp
bmRWaXJ0dWFsQWNjb3VudCA9IHVzZUNhbGxiYWNrKAogICAgKGN1cnJlbmN5OiBzdHJpbmcpID0+
IHZpcnR1YWxBY2NvdW50cy5maW5kKHYgPT4gdi5jdXJyZW5jeSA9PT0gY3VycmVuY3kpID8/IG51
bGwsCiAgICBbdmlydHVhbEFjY291bnRzXSwKICApCgogIC8vIEVuZG9yc2VtZW50IHN0YXR1cyBm
b3IgYSBjdXJyZW5jeTogJ2FwcHJvdmVkJyB8ICdwZW5kaW5nJyB8ICd1bmF2YWlsYWJsZScuCiAg
Ly8gJ3BlbmRpbmcnID0gdGhlIGN1c3RvbWVyIGhhcyB0aGUgZW5kb3JzZW1lbnQgcmVjb3JkIGJ1
dCBpdCBpc24ndCBhcHByb3ZlZAogIC8vIHlldDsgJ3VuYXZhaWxhYmxlJyA9IG5vIGVuZG9yc2Vt
ZW50IHJlY29yZCBhdCBhbGwgZm9yIHRoYXQgY3VycmVuY3kuCiAgY29uc3QgZW5kb3JzZW1lbnRG
b3IgPSB1c2VDYWxsYmFjaygKICAgIChjdXJyZW5jeTogc3RyaW5nKTogJ2FwcHJvdmVkJyB8ICdw
ZW5kaW5nJyB8ICd1bmF2YWlsYWJsZScgPT4gewogICAgICBjb25zdCBlID0gZW5kb3JzZW1lbnRz
W2N1cnJlbmN5XQogICAgICBpZiAoIWUpIHJldHVybiAndW5hdmFpbGFibGUnCiAgICAgIHJldHVy
biBlLmFwcHJvdmVkID8gJ2FwcHJvdmVkJyA6ICdwZW5kaW5nJwogICAgfSwKICAgIFtlbmRvcnNl
bWVudHNdLAogICkKCiAgcmV0dXJuIHsKICAgIGNvcnJpZG9ycywgY29ycmlkb3JzTG9hZGluZywK
ICAgIHZpcnR1YWxBY2NvdW50cywgZmluZFZpcnR1YWxBY2NvdW50LAogICAgZW5kb3JzZW1lbnRz
LCBlbmRvcnNlbWVudEZvciwKICAgIGNyZWF0aW5nLCBlcnJvciwKICAgIGxvYWRDb3JyaWRvcnMs
IGxvYWRWaXJ0dWFsQWNjb3VudHMsIGxvYWRFbmRvcnNlbWVudHMsCiAgICBjcmVhdGVWaXJ0dWFs
QWNjb3VudCwgZ2V0QWN0aXZpdHksCiAgfQp9Cg==
B64_FIXHOOK

if ! base64 --decode "$WORK/FIXHOOK.b64" > "$WORK/FIXHOOK.out" 2>/dev/null; then
  echo "✗ decode failed — nothing written." >&2; exit 1; fi
if [ ! -s "$WORK/FIXHOOK.out" ]; then echo "✗ decoded empty." >&2; exit 1; fi
for needle in "endorsementFor" "loadEndorsements" "export function useRamp" "export function useOnramp" "createVirtualAccount" "getActivity"; do
  if ! grep -qF "$needle" "$WORK/FIXHOOK.out"; then
    echo "✗ safety check failed: new file missing '$needle' — aborting, nothing written." >&2; exit 1; fi
done
if [ ! -f "$WEB_DIR/$F_HOOK" ]; then echo "✗ Missing $F_HOOK" >&2; exit 1; fi
cp -f "$WEB_DIR/$F_HOOK" "$BACKUP_DIR/${F_HOOK//\//__}.$STAMP.bak"
echo "EDIT|$F_HOOK" >> "$MANIFEST"
cp -f "$WORK/FIXHOOK.out" "$WEB_DIR/$F_HOOK"
echo "  ~ restored $F_HOOK (backup saved)"
echo ""
echo "✓ Fix applied."
echo "  EDIT $F_HOOK  (backup → $BACKUP_DIR; revert: bash $0 --revert)"
echo ""
echo "Now:"
echo "  cd \"$WEB_DIR\" && npx tsc --noEmit && npm run build"
echo "  (commit + push together with the Phase 4 edge-states change)"
echo ""
echo "This restores the 2b endorsement wiring the web hook was missing, so the"
echo "endorsement-gated currency grid works and Phase 4's page compiles."
