// AUTO-GENERATED from currency-codes (ISO 4217) + i18n-iso-countries.
// 179 currencies. Do not hand-edit; regenerate if the ISO list changes.
// Availability in the UI is driven by the LIVE rate feed, not this list — an
// entry here only appears in pickers if the rate oracle has a rate for it.
export interface CurrencyMeta {
  code: string
  name: string
  country: string
  flag: string
  countries: string[]   // all member countries, for search-by-country
}

export const CURRENCY_REGISTRY: CurrencyMeta[] = [
  { code: "AED", name: "UAE Dirham", country: "United Arab Emirates", flag: "🇦🇪", countries: ["United Arab Emirates"] },
  { code: "AFN", name: "Afghani", country: "Afghanistan", flag: "🇦🇫", countries: ["Afghanistan"] },
  { code: "ALL", name: "Lek", country: "Albania", flag: "🇦🇱", countries: ["Albania"] },
  { code: "AMD", name: "Armenian Dram", country: "Armenia", flag: "🇦🇲", countries: ["Armenia"] },
  { code: "ANG", name: "Netherlands Antillean Guilder", country: "Curaçao", flag: "🇨🇼", countries: ["Curaçao","Sint Maarten"] },
  { code: "AOA", name: "Kwanza", country: "Angola", flag: "🇦🇴", countries: ["Angola"] },
  { code: "ARS", name: "Argentine Peso", country: "Argentina", flag: "🇦🇷", countries: ["Argentina"] },
  { code: "AUD", name: "Australian Dollar", country: "Australia", flag: "🇦🇺", countries: ["Australia","Christmas Island","Cocos Islands","Heard Island and Mcdonald Islands","Kiribati","Nauru","Norfolk Island","Tuvalu"] },
  { code: "AWG", name: "Aruban Florin", country: "Aruba", flag: "🇦🇼", countries: ["Aruba"] },
  { code: "AZN", name: "Azerbaijan Manat", country: "Azerbaijan", flag: "🇦🇿", countries: ["Azerbaijan"] },
  { code: "BAM", name: "Convertible Mark", country: "Bosnia and Herzegovina", flag: "🇧🇦", countries: ["Bosnia and Herzegovina"] },
  { code: "BBD", name: "Barbados Dollar", country: "Barbados", flag: "🇧🇧", countries: ["Barbados"] },
  { code: "BDT", name: "Taka", country: "Bangladesh", flag: "🇧🇩", countries: ["Bangladesh"] },
  { code: "BGN", name: "Bulgarian Lev", country: "Bulgaria", flag: "🇧🇬", countries: ["Bulgaria"] },
  { code: "BHD", name: "Bahraini Dinar", country: "Bahrain", flag: "🇧🇭", countries: ["Bahrain"] },
  { code: "BIF", name: "Burundi Franc", country: "Burundi", flag: "🇧🇮", countries: ["Burundi"] },
  { code: "BMD", name: "Bermudian Dollar", country: "Bermuda", flag: "🇧🇲", countries: ["Bermuda"] },
  { code: "BND", name: "Brunei Dollar", country: "Brunei Darussalam", flag: "🇧🇳", countries: ["Brunei Darussalam"] },
  { code: "BOB", name: "Boliviano", country: "Bolivia", flag: "🇧🇴", countries: ["Bolivia"] },
  { code: "BOV", name: "Mvdol", country: "Bolivia", flag: "🇧🇴", countries: ["Bolivia"] },
  { code: "BRL", name: "Brazilian Real", country: "Brazil", flag: "🇧🇷", countries: ["Brazil"] },
  { code: "BSD", name: "Bahamian Dollar", country: "Bahamas", flag: "🇧🇸", countries: ["Bahamas"] },
  { code: "BTN", name: "Ngultrum", country: "Bhutan", flag: "🇧🇹", countries: ["Bhutan"] },
  { code: "BWP", name: "Pula", country: "Botswana", flag: "🇧🇼", countries: ["Botswana"] },
  { code: "BYN", name: "Belarusian Ruble", country: "Belarus", flag: "🇧🇾", countries: ["Belarus"] },
  { code: "BZD", name: "Belize Dollar", country: "Belize", flag: "🇧🇿", countries: ["Belize"] },
  { code: "CAD", name: "Canadian Dollar", country: "Canada", flag: "🇨🇦", countries: ["Canada"] },
  { code: "CDF", name: "Congolese Franc", country: "Congo", flag: "🇨🇬", countries: ["Congo"] },
  { code: "CHE", name: "WIR Euro", country: "Switzerland", flag: "🇨🇭", countries: ["Switzerland"] },
  { code: "CHF", name: "Swiss Franc", country: "Switzerland", flag: "🇨🇭", countries: ["Liechtenstein","Switzerland"] },
  { code: "CHW", name: "WIR Franc", country: "Switzerland", flag: "🇨🇭", countries: ["Switzerland"] },
  { code: "CLF", name: "Unidad de Fomento", country: "Chile", flag: "🇨🇱", countries: ["Chile"] },
  { code: "CLP", name: "Chilean Peso", country: "Chile", flag: "🇨🇱", countries: ["Chile"] },
  { code: "CNY", name: "Yuan Renminbi", country: "China", flag: "🇨🇳", countries: ["China"] },
  { code: "COP", name: "Colombian Peso", country: "Colombia", flag: "🇨🇴", countries: ["Colombia"] },
  { code: "COU", name: "Unidad de Valor Real", country: "Colombia", flag: "🇨🇴", countries: ["Colombia"] },
  { code: "CRC", name: "Costa Rican Colon", country: "Costa Rica", flag: "🇨🇷", countries: ["Costa Rica"] },
  { code: "CUC", name: "Peso Convertible", country: "Cuba", flag: "🇨🇺", countries: ["Cuba"] },
  { code: "CUP", name: "Cuban Peso", country: "Cuba", flag: "🇨🇺", countries: ["Cuba"] },
  { code: "CVE", name: "Cabo Verde Escudo", country: "Cabo Verde", flag: "🌍", countries: ["Cabo Verde"] },
  { code: "CZK", name: "Czech Koruna", country: "Czechia", flag: "🇨🇿", countries: ["Czechia"] },
  { code: "DJF", name: "Djibouti Franc", country: "Djibouti", flag: "🇩🇯", countries: ["Djibouti"] },
  { code: "DKK", name: "Danish Krone", country: "Denmark", flag: "🇩🇰", countries: ["Denmark","Faroe Islands","Greenland"] },
  { code: "DOP", name: "Dominican Peso", country: "Dominican Republic", flag: "🇩🇴", countries: ["Dominican Republic"] },
  { code: "DZD", name: "Algerian Dinar", country: "Algeria", flag: "🇩🇿", countries: ["Algeria"] },
  { code: "EGP", name: "Egyptian Pound", country: "Egypt", flag: "🇪🇬", countries: ["Egypt"] },
  { code: "ERN", name: "Nakfa", country: "Eritrea", flag: "🇪🇷", countries: ["Eritrea"] },
  { code: "ETB", name: "Ethiopian Birr", country: "Ethiopia", flag: "🇪🇹", countries: ["Ethiopia"] },
  { code: "EUR", name: "Euro", country: "Eurozone", flag: "🇪🇺", countries: ["Åland Islands","Andorra","Austria","Belgium","Croatia","Cyprus","Estonia","European Union","Finland","France","French Guiana","French Southern Territories","Germany","Greece","Guadeloupe","Holy See","Ireland","Italy","Latvia","Lithuania","Luxembourg","Malta","Martinique","Mayotte","Monaco","Montenegro","Netherlands","Portugal","Réunion","Saint Barthélemy","Saint Martin","Saint Pierre and Miquelon","San Marino","Slovakia","Slovenia","Spain"] },
  { code: "FJD", name: "Fiji Dollar", country: "Fiji", flag: "🇫🇯", countries: ["Fiji"] },
  { code: "FKP", name: "Falkland Islands Pound", country: "Falkland Islands[Malvinas]", flag: "🌍", countries: ["Falkland Islands[Malvinas]"] },
  { code: "GBP", name: "Pound Sterling", country: "United Kingdom", flag: "🇬🇧", countries: ["Guernsey","Isle of Man","Jersey","United Kingdom of Great Britain and Northern Ireland"] },
  { code: "GEL", name: "Lari", country: "Georgia", flag: "🇬🇪", countries: ["Georgia"] },
  { code: "GHS", name: "Ghana Cedi", country: "Ghana", flag: "🇬🇭", countries: ["Ghana"] },
  { code: "GIP", name: "Gibraltar Pound", country: "Gibraltar", flag: "🇬🇮", countries: ["Gibraltar"] },
  { code: "GMD", name: "Dalasi", country: "Gambia", flag: "🇬🇲", countries: ["Gambia"] },
  { code: "GNF", name: "Guinean Franc", country: "Guinea", flag: "🇬🇳", countries: ["Guinea"] },
  { code: "GTQ", name: "Quetzal", country: "Guatemala", flag: "🇬🇹", countries: ["Guatemala"] },
  { code: "GYD", name: "Guyana Dollar", country: "Guyana", flag: "🇬🇾", countries: ["Guyana"] },
  { code: "HKD", name: "Hong Kong Dollar", country: "Hong Kong", flag: "🇭🇰", countries: ["Hong Kong"] },
  { code: "HNL", name: "Lempira", country: "Honduras", flag: "🇭🇳", countries: ["Honduras"] },
  { code: "HTG", name: "Gourde", country: "Haiti", flag: "🇭🇹", countries: ["Haiti"] },
  { code: "HUF", name: "Forint", country: "Hungary", flag: "🇭🇺", countries: ["Hungary"] },
  { code: "IDR", name: "Rupiah", country: "Indonesia", flag: "🇮🇩", countries: ["Indonesia"] },
  { code: "ILS", name: "New Israeli Sheqel", country: "Israel", flag: "🇮🇱", countries: ["Israel"] },
  { code: "INR", name: "Indian Rupee", country: "India", flag: "🇮🇳", countries: ["Bhutan","India"] },
  { code: "IQD", name: "Iraqi Dinar", country: "Iraq", flag: "🇮🇶", countries: ["Iraq"] },
  { code: "IRR", name: "Iranian Rial", country: "Iran", flag: "🇮🇷", countries: ["Iran"] },
  { code: "ISK", name: "Iceland Krona", country: "Iceland", flag: "🇮🇸", countries: ["Iceland"] },
  { code: "JMD", name: "Jamaican Dollar", country: "Jamaica", flag: "🇯🇲", countries: ["Jamaica"] },
  { code: "JOD", name: "Jordanian Dinar", country: "Jordan", flag: "🇯🇴", countries: ["Jordan"] },
  { code: "JPY", name: "Yen", country: "Japan", flag: "🇯🇵", countries: ["Japan"] },
  { code: "KES", name: "Kenyan Shilling", country: "Kenya", flag: "🇰🇪", countries: ["Kenya"] },
  { code: "KGS", name: "Som", country: "Kyrgyzstan", flag: "🇰🇬", countries: ["Kyrgyzstan"] },
  { code: "KHR", name: "Riel", country: "Cambodia", flag: "🇰🇭", countries: ["Cambodia"] },
  { code: "KMF", name: "Comorian Franc ", country: "Comoros", flag: "🇰🇲", countries: ["Comoros"] },
  { code: "KPW", name: "North Korean Won", country: "Korea", flag: "🌍", countries: ["Korea"] },
  { code: "KRW", name: "Won", country: "Korea", flag: "🌍", countries: ["Korea"] },
  { code: "KWD", name: "Kuwaiti Dinar", country: "Kuwait", flag: "🇰🇼", countries: ["Kuwait"] },
  { code: "KYD", name: "Cayman Islands Dollar", country: "Cayman Islands", flag: "🇰🇾", countries: ["Cayman Islands"] },
  { code: "KZT", name: "Tenge", country: "Kazakhstan", flag: "🇰🇿", countries: ["Kazakhstan"] },
  { code: "LAK", name: "Lao Kip", country: "Lao People’s Democratic Republic", flag: "🌍", countries: ["Lao People’s Democratic Republic"] },
  { code: "LBP", name: "Lebanese Pound", country: "Lebanon", flag: "🇱🇧", countries: ["Lebanon"] },
  { code: "LKR", name: "Sri Lanka Rupee", country: "Sri Lanka", flag: "🇱🇰", countries: ["Sri Lanka"] },
  { code: "LRD", name: "Liberian Dollar", country: "Liberia", flag: "🇱🇷", countries: ["Liberia"] },
  { code: "LSL", name: "Loti", country: "Lesotho", flag: "🇱🇸", countries: ["Lesotho"] },
  { code: "LYD", name: "Libyan Dinar", country: "Libya", flag: "🇱🇾", countries: ["Libya"] },
  { code: "MAD", name: "Moroccan Dirham", country: "Morocco", flag: "🇲🇦", countries: ["Morocco","Western Sahara"] },
  { code: "MDL", name: "Moldovan Leu", country: "Moldova", flag: "🌍", countries: ["Moldova"] },
  { code: "MGA", name: "Malagasy Ariary", country: "Madagascar", flag: "🇲🇬", countries: ["Madagascar"] },
  { code: "MKD", name: "Denar", country: "North Macedonia", flag: "🇲🇰", countries: ["North Macedonia"] },
  { code: "MMK", name: "Kyat", country: "Myanmar", flag: "🇲🇲", countries: ["Myanmar"] },
  { code: "MNT", name: "Tugrik", country: "Mongolia", flag: "🇲🇳", countries: ["Mongolia"] },
  { code: "MOP", name: "Pataca", country: "Macao", flag: "🇲🇴", countries: ["Macao"] },
  { code: "MRU", name: "Ouguiya", country: "Mauritania", flag: "🇲🇷", countries: ["Mauritania"] },
  { code: "MUR", name: "Mauritius Rupee", country: "Mauritius", flag: "🇲🇺", countries: ["Mauritius"] },
  { code: "MVR", name: "Rufiyaa", country: "Maldives", flag: "🇲🇻", countries: ["Maldives"] },
  { code: "MWK", name: "Malawi Kwacha", country: "Malawi", flag: "🇲🇼", countries: ["Malawi"] },
  { code: "MXN", name: "Mexican Peso", country: "Mexico", flag: "🇲🇽", countries: ["Mexico"] },
  { code: "MXV", name: "Mexican Unidad de Inversion (UDI)", country: "Mexico", flag: "🇲🇽", countries: ["Mexico"] },
  { code: "MYR", name: "Malaysian Ringgit", country: "Malaysia", flag: "🇲🇾", countries: ["Malaysia"] },
  { code: "MZN", name: "Mozambique Metical", country: "Mozambique", flag: "🇲🇿", countries: ["Mozambique"] },
  { code: "NAD", name: "Namibia Dollar", country: "Namibia", flag: "🇳🇦", countries: ["Namibia"] },
  { code: "NGN", name: "Naira", country: "Nigeria", flag: "🇳🇬", countries: ["Nigeria"] },
  { code: "NIO", name: "Cordoba Oro", country: "Nicaragua", flag: "🇳🇮", countries: ["Nicaragua"] },
  { code: "NOK", name: "Norwegian Krone", country: "Norway", flag: "🇳🇴", countries: ["Bouvet Island","Norway","Svalbard and Jan Mayen"] },
  { code: "NPR", name: "Nepalese Rupee", country: "Nepal", flag: "🇳🇵", countries: ["Nepal"] },
  { code: "NZD", name: "New Zealand Dollar", country: "New Zealand", flag: "🇳🇿", countries: ["Cook Islands","New Zealand","Niue","Pitcairn","Tokelau"] },
  { code: "OMR", name: "Rial Omani", country: "Oman", flag: "🇴🇲", countries: ["Oman"] },
  { code: "PAB", name: "Balboa", country: "Panama", flag: "🇵🇦", countries: ["Panama"] },
  { code: "PEN", name: "Sol", country: "Peru", flag: "🇵🇪", countries: ["Peru"] },
  { code: "PGK", name: "Kina", country: "Papua New Guinea", flag: "🇵🇬", countries: ["Papua New Guinea"] },
  { code: "PHP", name: "Philippine Peso", country: "Philippines", flag: "🇵🇭", countries: ["Philippines"] },
  { code: "PKR", name: "Pakistan Rupee", country: "Pakistan", flag: "🇵🇰", countries: ["Pakistan"] },
  { code: "PLN", name: "Zloty", country: "Poland", flag: "🇵🇱", countries: ["Poland"] },
  { code: "PYG", name: "Guarani", country: "Paraguay", flag: "🇵🇾", countries: ["Paraguay"] },
  { code: "QAR", name: "Qatari Rial", country: "Qatar", flag: "🇶🇦", countries: ["Qatar"] },
  { code: "RON", name: "Romanian Leu", country: "Romania", flag: "🇷🇴", countries: ["Romania"] },
  { code: "RSD", name: "Serbian Dinar", country: "Serbia", flag: "🇷🇸", countries: ["Serbia"] },
  { code: "RUB", name: "Russian Ruble", country: "Russian Federation", flag: "🇷🇺", countries: ["Russian Federation"] },
  { code: "RWF", name: "Rwanda Franc", country: "Rwanda", flag: "🇷🇼", countries: ["Rwanda"] },
  { code: "SAR", name: "Saudi Riyal", country: "Saudi Arabia", flag: "🇸🇦", countries: ["Saudi Arabia"] },
  { code: "SBD", name: "Solomon Islands Dollar", country: "Solomon Islands", flag: "🇸🇧", countries: ["Solomon Islands"] },
  { code: "SCR", name: "Seychelles Rupee", country: "Seychelles", flag: "🇸🇨", countries: ["Seychelles"] },
  { code: "SDG", name: "Sudanese Pound", country: "Sudan", flag: "🇸🇩", countries: ["Sudan"] },
  { code: "SEK", name: "Swedish Krona", country: "Sweden", flag: "🇸🇪", countries: ["Sweden"] },
  { code: "SGD", name: "Singapore Dollar", country: "Singapore", flag: "🇸🇬", countries: ["Singapore"] },
  { code: "SHP", name: "Saint Helena Pound", country: "Saint Helena, Ascension and Tristan Da Cunha", flag: "🌍", countries: ["Saint Helena, Ascension and Tristan Da Cunha"] },
  { code: "SLE", name: "Leone", country: "Sierra Leone", flag: "🇸🇱", countries: ["Sierra Leone"] },
  { code: "SOS", name: "Somali Shilling", country: "Somalia", flag: "🇸🇴", countries: ["Somalia"] },
  { code: "SRD", name: "Surinam Dollar", country: "Suriname", flag: "🇸🇷", countries: ["Suriname"] },
  { code: "SSP", name: "South Sudanese Pound", country: "South Sudan", flag: "🇸🇸", countries: ["South Sudan"] },
  { code: "STN", name: "Dobra", country: "Sao Tome and Principe", flag: "🇸🇹", countries: ["Sao Tome and Principe"] },
  { code: "SVC", name: "El Salvador Colon", country: "El Salvador", flag: "🇸🇻", countries: ["El Salvador"] },
  { code: "SYP", name: "Syrian Pound", country: "Syrian Arab Republic", flag: "🇸🇾", countries: ["Syrian Arab Republic"] },
  { code: "SZL", name: "Lilangeni", country: "Eswatini", flag: "🇸🇿", countries: ["Eswatini"] },
  { code: "THB", name: "Baht", country: "Thailand", flag: "🇹🇭", countries: ["Thailand"] },
  { code: "TJS", name: "Somoni", country: "Tajikistan", flag: "🇹🇯", countries: ["Tajikistan"] },
  { code: "TMT", name: "Turkmenistan New Manat", country: "Turkmenistan", flag: "🇹🇲", countries: ["Turkmenistan"] },
  { code: "TND", name: "Tunisian Dinar", country: "Tunisia", flag: "🇹🇳", countries: ["Tunisia"] },
  { code: "TOP", name: "Pa’anga", country: "Tonga", flag: "🇹🇴", countries: ["Tonga"] },
  { code: "TRY", name: "Turkish Lira", country: "Türki̇ye", flag: "🌍", countries: ["Türki̇ye"] },
  { code: "TTD", name: "Trinidad and Tobago Dollar", country: "Trinidad and Tobago", flag: "🇹🇹", countries: ["Trinidad and Tobago"] },
  { code: "TWD", name: "New Taiwan Dollar", country: "Taiwan", flag: "🇹🇼", countries: ["Taiwan"] },
  { code: "TZS", name: "Tanzanian Shilling", country: "Tanzania, United Republic Of", flag: "🌍", countries: ["Tanzania, United Republic Of"] },
  { code: "UAH", name: "Hryvnia", country: "Ukraine", flag: "🇺🇦", countries: ["Ukraine"] },
  { code: "UGX", name: "Uganda Shilling", country: "Uganda", flag: "🇺🇬", countries: ["Uganda"] },
  { code: "USD", name: "US Dollar", country: "United States", flag: "🇺🇸", countries: ["American Samoa","Bonaire, Sint Eustatius and Saba","British Indian Ocean Territory","Ecuador","El Salvador","Guam","Haiti","Marshall Islands","Micronesia","Northern Mariana Islands","Palau","Panama","Puerto Rico","Timor-Leste","Turks and Caicos Islands","United States Minor Outlying Islands","United States of America","Virgin Islands"] },
  { code: "USN", name: "US Dollar (Next day)", country: "United States of America", flag: "🇺🇸", countries: ["United States of America"] },
  { code: "UYI", name: "Uruguay Peso en Unidades Indexadas (UI)", country: "Uruguay", flag: "🇺🇾", countries: ["Uruguay"] },
  { code: "UYU", name: "Peso Uruguayo", country: "Uruguay", flag: "🇺🇾", countries: ["Uruguay"] },
  { code: "UYW", name: "Unidad Previsional", country: "Uruguay", flag: "🇺🇾", countries: ["Uruguay"] },
  { code: "UZS", name: "Uzbekistan Sum", country: "Uzbekistan", flag: "🇺🇿", countries: ["Uzbekistan"] },
  { code: "VED", name: "Bolívar Soberano", country: "Venezuela", flag: "🇻🇪", countries: ["Venezuela"] },
  { code: "VES", name: "Bolívar Soberano", country: "Venezuela", flag: "🇻🇪", countries: ["Venezuela"] },
  { code: "VND", name: "Dong", country: "Viet Nam", flag: "🌍", countries: ["Viet Nam"] },
  { code: "VUV", name: "Vatu", country: "Vanuatu", flag: "🇻🇺", countries: ["Vanuatu"] },
  { code: "WST", name: "Tala", country: "Samoa", flag: "🇼🇸", countries: ["Samoa"] },
  { code: "XAF", name: "CFA Franc BEAC", country: "Central Africa (CFA)", flag: "🇨🇲", countries: ["Cameroon","Central African Republic","Chad","Congo","Equatorial Guinea","Gabon"] },
  { code: "XAG", name: "Silver", country: "Zz11_silver", flag: "🌍", countries: ["Zz11_silver"] },
  { code: "XAU", name: "Gold", country: "Zz08_gold", flag: "🌍", countries: ["Zz08_gold"] },
  { code: "XBA", name: "Bond Markets Unit European Composite Unit (EURCO)", country: "Zz01_bond Markets Unit European_eurco", flag: "🌍", countries: ["Zz01_bond Markets Unit European_eurco"] },
  { code: "XBB", name: "Bond Markets Unit European Monetary Unit (E.M.U.-6)", country: "Zz02_bond Markets Unit European_emu-6", flag: "🌍", countries: ["Zz02_bond Markets Unit European_emu-6"] },
  { code: "XBC", name: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", country: "Zz03_bond Markets Unit European_eua-9", flag: "🌍", countries: ["Zz03_bond Markets Unit European_eua-9"] },
  { code: "XBD", name: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", country: "Zz04_bond Markets Unit European_eua-17", flag: "🌍", countries: ["Zz04_bond Markets Unit European_eua-17"] },
  { code: "XCD", name: "East Caribbean Dollar", country: "East Caribbean", flag: "🇦🇬", countries: ["Anguilla","Antigua and Barbuda","Dominica","Grenada","Montserrat","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines"] },
  { code: "XDR", name: "SDR (Special Drawing Right)", country: "International Monetary Fund", flag: "🌍", countries: ["International Monetary Fund"] },
  { code: "XOF", name: "CFA Franc BCEAO", country: "West Africa (CFA)", flag: "🇸🇳", countries: ["Benin","Burkina Faso","Côte D'ivoire","Guinea-Bissau","Mali","Niger","Senegal","Togo"] },
  { code: "XPD", name: "Palladium", country: "Zz09_palladium", flag: "🌍", countries: ["Zz09_palladium"] },
  { code: "XPF", name: "CFP Franc", country: "French Polynesia", flag: "🇵🇫", countries: ["French Polynesia","New Caledonia","Wallis and Futuna"] },
  { code: "XPT", name: "Platinum", country: "Zz10_platinum", flag: "🌍", countries: ["Zz10_platinum"] },
  { code: "XSU", name: "Sucre", country: "Sistema Unitario De Compensacion Regional De Pagos \"Sucre\"", flag: "🌍", countries: ["Sistema Unitario De Compensacion Regional De Pagos \"Sucre\""] },
  { code: "XTS", name: "Codes specifically reserved for testing purposes", country: "Zz06_testing_code", flag: "🌍", countries: ["Zz06_testing_code"] },
  { code: "XUA", name: "ADB Unit of Account", country: "Member Countries of the African Development Bank Group", flag: "🌍", countries: ["Member Countries of the African Development Bank Group"] },
  { code: "XXX", name: "The codes assigned for transactions where no currency is involved", country: "Zz07_no_currency", flag: "🌍", countries: ["Zz07_no_currency"] },
  { code: "YER", name: "Yemeni Rial", country: "Yemen", flag: "🇾🇪", countries: ["Yemen"] },
  { code: "ZAR", name: "Rand", country: "South Africa", flag: "🇿🇦", countries: ["Lesotho","Namibia","South Africa"] },
  { code: "ZMW", name: "Zambian Kwacha", country: "Zambia", flag: "🇿🇲", countries: ["Zambia"] },
  { code: "ZWG", name: "Zimbabwe Gold", country: "Zimbabwe", flag: "🇿🇼", countries: ["Zimbabwe"] },
]

export const CURRENCY_BY_CODE: Record<string, CurrencyMeta> =
  Object.fromEntries(CURRENCY_REGISTRY.map(c => [c.code, c]))

// Fuzzy match by code OR any country name. Returns matching currency codes.
export function searchCurrencies(query: string): CurrencyMeta[] {
  const q = query.trim().toLowerCase()
  if (!q) return CURRENCY_REGISTRY
  return CURRENCY_REGISTRY.filter(c =>
    c.code.toLowerCase().includes(q) ||
    c.name.toLowerCase().includes(q) ||
    c.country.toLowerCase().includes(q) ||
    c.countries.some(n => n.toLowerCase().includes(q))
  )
}
